2021-12-29 12:41:35.720 | SUCCESS  | __main__:parse:182 - handle [1/4] | topic=`Robotics` subtopic=`Visual Localization`
2021-12-29 12:41:35.792 | SUCCESS  | __main__:parse:182 - handle [2/4] | topic=`Robotics` subtopic=`SLAM`
2021-12-29 12:41:35.814 | SUCCESS  | __main__:parse:182 - handle [3/4] | topic=`Robotics` subtopic=`SFM`
2021-12-29 12:41:35.826 | SUCCESS  | __main__:parse:182 - handle [4/4] | topic=`Robotics` subtopic=`Robotics`
2021-12-29 12:42:36.282 | SUCCESS  | __main__:parse:182 - handle [1/4] | topic=`Robotics` subtopic=`SLAM`
2021-12-29 12:42:36.698 | SUCCESS  | __main__:parse:182 - handle [2/4] | topic=`Robotics` subtopic=`SFM`
2021-12-29 12:42:37.102 | SUCCESS  | __main__:parse:182 - handle [3/4] | topic=`Robotics` subtopic=`Robotics`
2021-12-29 12:42:37.196 | SUCCESS  | __main__:parse:182 - handle [4/4] | topic=`Robotics` subtopic=`Visual Localization`
2021-12-29 12:45:35.903 | SUCCESS  | __main__:parse:182 - handle [1/4] | topic=`Robotics` subtopic=`SLAM`
2021-12-29 12:45:35.926 | SUCCESS  | __main__:parse:182 - handle [2/4] | topic=`Robotics` subtopic=`SFM`
2021-12-29 12:45:35.958 | SUCCESS  | __main__:parse:182 - handle [3/4] | topic=`Robotics` subtopic=`Robotics`
2021-12-29 12:45:36.042 | SUCCESS  | __main__:parse:182 - handle [4/4] | topic=`Robotics` subtopic=`Visual Localization`
2021-12-29 12:47:29.131 | SUCCESS  | __main__:parse:182 - handle [1/4] | topic=`Robotics` subtopic=`Visual Localization`
2021-12-29 12:47:29.178 | SUCCESS  | __main__:parse:182 - handle [2/4] | topic=`Robotics` subtopic=`SFM`
2021-12-29 12:47:29.214 | SUCCESS  | __main__:parse:182 - handle [3/4] | topic=`Robotics` subtopic=`Robotics`
2021-12-29 12:47:29.266 | SUCCESS  | __main__:parse:182 - handle [4/4] | topic=`Robotics` subtopic=`SLAM`
2021-12-29 12:50:53.192 | SUCCESS  | __main__:parse:182 - handle [1/4] | topic=`Robotics` subtopic=`SLAM`
2021-12-29 12:50:53.565 | SUCCESS  | __main__:parse:182 - handle [2/4] | topic=`Robotics` subtopic=`SFM`
2021-12-29 12:50:53.771 | SUCCESS  | __main__:parse:182 - handle [3/4] | topic=`Robotics` subtopic=`Visual Localization`
2021-12-29 12:50:54.101 | SUCCESS  | __main__:parse:182 - handle [4/4] | topic=`Robotics` subtopic=`Robotics`
2021-12-29 12:52:27.554 | SUCCESS  | __main__:parse:182 - handle [1/4] | topic=`Robotics` subtopic=`Robotics`
2021-12-29 12:52:27.795 | SUCCESS  | __main__:parse:182 - handle [2/4] | topic=`Robotics` subtopic=`SFM`
2021-12-29 12:52:27.834 | SUCCESS  | __main__:parse:182 - handle [3/4] | topic=`Robotics` subtopic=`Visual Localization`
2021-12-29 12:52:27.944 | SUCCESS  | __main__:parse:182 - handle [4/4] | topic=`Robotics` subtopic=`SLAM`
2021-12-29 12:59:49.118 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (2092), thread 'MainThread' (139750478002480):
Traceback (most recent call last):

  File "main.py", line 370, in <module>
    Fire(Scaffold)
    │    └ <class '__main__.Scaffold'>
    └ <function Fire at 0x7f1a2ef86a60>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 'main.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(completion=None, help=False, interactive=False, separator='-', trace=False, verbose=False)
                      │     │          └ ['run', '--env=production', '--power=16']
                      │     └ <class '__main__.Scaffold'>
                      └ <function _Fire at 0x7f1a2eb30dc0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x7f1a2eb30ee0>
    └ <function Scaffold.run at 0x7f1a2ea49430>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ ['production', 16]
                └ <function Scaffold.run at 0x7f1a2ea49430>

  File "main.py", line 348, in run
    context = ToolBox.get_yaml_data()
              │       └ <staticmethod object at 0x7f1a2fb9ac40>
              └ <class '__main__.ToolBox'>

  File "main.py", line 49, in get_yaml_data
    data = yaml.load(f, Loader=yaml.SafeLoader)
           │    │    │         │    └ <class 'yaml.loader.SafeLoader'>
           │    │    │         └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>
           │    │    └ <_io.TextIOWrapper name='/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml' mode='r' encoding='utf8'>
           │    └ <function load at 0x7f1a2ef845e0>
           └ <module 'yaml' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py'>

  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           │      └ <function BaseConstructor.get_single_data at 0x7f1a2efcaee0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           │    └ <function Composer.get_single_node at 0x7f1a2efca5e0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               │    └ <function Composer.compose_document at 0x7f1a2efca670>
               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           │    └ <function Composer.compose_node at 0x7f1a2efca700>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           │    │                    └ None
           │    └ <function Composer.compose_mapping_node at 0x7f1a2efca8b0>
           └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              │    │           └ <class 'yaml.events.MappingEndEvent'>
              │    └ <function Parser.check_event at 0x7f1a2efc9160>
              └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
    │    │               │    └ None
    │    │               └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
    │    └ None
    └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
          │                                            │    └ [<yaml.error.Mark object at 0x7f1a2ea47fd0>]
          │                                            └ <yaml.loader.SafeLoader object at 0x7f1a2ea47580>
          └ <class 'yaml.parser.ParserError'>

yaml.parser.ParserError: while parsing a block mapping
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
  in "/home/runner/work/arxiv-daily/arxiv-daily/database/topic.yml", line 5, column 3
